### PR TITLE
Add HttpMethod to web jar

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
@aureamunoz please don't release a new version yet, since we may need more changes.

**Comment by aureamunoz** [comment]
No, I won't. I didn't see the 'approve' option it's why I merged it

**Comment by galderz** [comment]
Yeah, maybe a bit too quick to merge until we've figured out if it's really needed.

**Comment by geoand** [comment]
It can't hurt, so no problem in merging, but let's indeed wait to see if we will need any more changes before releasing.

**Pull request merged**
