### PR TITLE
Add Spring Cache annotations

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
@aureamunoz can you do a release with this change when you have some time?

**Comment by aureamunoz** [comment]
sure

**Comment by geoand** [comment]
Thanks!

**Comment by aureamunoz** [comment]
Release done: https://repo.maven.apache.org/maven2/io/quarkus/quarkus-spring-api/5.2.SP2/

**Comment by geoand** [comment]
Awesome, thanks a lot!

**Pull request merged**
